### ISSUE TITLE
Provide libprotobuff version 2.6.1

### ISSUE THREAD

**Issue by phreed** [conda-forge/libprotobuf-feedstock#107]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I do not think this qualifies as a bug but none of the other labels looked more appropriate.

The earliest available version is 3.5.1

I would like to add an older source version to the feedstock.
Specifically, https://github.com/conda-forge/libprotobuf-feedstock
```
{% set version = "2.6.1" %}
```
https://github.com/protocolbuffers/protobuf/releases/tag/v2.6.1

### Installed packages

```shell
mamba list
libprotobuf  3.20.0   h7755175_0  conda-forge

The earliest version of libprotobuf...

mamba search libprotobuf
libprotobuf                    3.5.1          vc14_0  conda-forge
```

### Environment info

```shell
not relevant
```

**Comment by xylar** [comment]
@phreed, I'm new as a maintainer to this feedstock.

I'm wondering if this is still something you want to pursue.  I would be willing to help but I have to anticipate that building a package from 2014 might be very difficult.  A c++ library without too many dependencies has a higher chance of succeeding than something like a complex python package.
