### ISSUE TITLE
libprotobuf versioning for latest (21.x) releases may not be correct

### ISSUE THREAD

**Issue by xylar** [conda-forge/libprotobuf-feedstock#122]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

It seems that with repo tags 21.x, the development repo for protobuf changed its approach.  It seems they now have different major version numbers for different assets.  See, for example:
https://github.com/protocolbuffers/protobuf/releases/tag/v21.5
It seems that `libprotobuf` should remain with v3.21.x, while the python package `protobuf` needs to have v4.21.x.  This is confusing to say the least but it's also not something where we can "go rogue" and do our own thing.  I think we've just been following the bot and/or the release tags in the move from 3.20.x to 21.x but I think we need to undo that.

More discussion related to this is at:
https://github.com/conda-forge/protobuf-feedstock/pull/147
https://github.com/conda-forge/protobuf-feedstock/pull/146#issuecomment-1149410254
https://github.com/conda-forge/admin-requests/pull/476

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by h-vetinari** [comment]
Egahds, that is pretty messed up. I thought they had just changed the versioning scheme to calver or something.

Can you send a PR to c-f/admin-requests to mark all builds with v>4 as broken?

**Comment by h-vetinari** [comment]
> Can you send a PR to c-f/admin-requests to mark all builds with v>4 as broken?

Ah, you did that already - great thanks! :)

**Comment by h-vetinari** [comment]
> > Can you send a PR to c-f/admin-requests to mark all builds with v>4 as broken?
> 
> Ah, you did that already - great thanks! :)

Clearly I should concentrate more on packing for my travels tomorrow. In any case, marking libprotobuf 21.x as broken is still going to be necessary.

**Comment by xylar** [comment]
Yes, this last one is right.  I marked only my own incorrect packages as broken from `protobuf`.  It remains to mark `libprotobuf` packages as broken and rebuild them with correct version numbers.

**Comment by xylar** [comment]
I made a PR to mark these as broken here: https://github.com/conda-forge/admin-requests/pull/477

**Comment by xylar** [comment]
closed via https://github.com/conda-forge/admin-requests/pull/477
