### ISSUE TITLE
web page shows v21.2 latest but files for v23.4 exist

### ISSUE THREAD

**Issue by igozali** [conda-forge/libprotobuf-feedstock#172]
### Comment:

Just curious why the homepage for https://anaconda.org/conda-forge/protobuf shows that only v21.2 is the latest.

![image](https://github.com/conda-forge/libprotobuf-feedstock/assets/1359333/d4c7c3fa-d9d6-461f-8976-511017d805a6)

but there actually are files for v23.4

![image](https://github.com/conda-forge/libprotobuf-feedstock/assets/1359333/955e5214-01ba-45bc-9149-29c24020145f)

**Comment by xylar** [comment]
We (I) mistakenly built some files with version 21.2 instead of 4.21.2. These have been marked as broken but even so, anaconda.org thinks that this erroneous version is the latest.  There isn't anything we can do about this.

**Comment by igozali** [comment]
Oh I see, thank you! The proper versioning scheme is `4.21.x` instead of `21.x`?

**Comment by h-vetinari** [comment]
This was done now, see #264
