### ISSUE TITLE
(lib)protobuf-python-headers

### ISSUE THREAD

**Issue by xhochy** [conda-forge/libprotobuf-feedstock#174]
### Comment:

We currently don't package the headers matching the Python implementation. There is also no script to install them (and they are probably only used by a small set of Google projects). As the headers are independent of the Python version, I would propose to add them to this repository as `libprotobuf-python-headers` via a `find python -name '*.h* | copy` approach.

**Comment by h-vetinari** [comment]
> I would propose to add them to this repository as `libprotobuf-python-headers` via a `find python -name '*.h* | copy` approach.

This would roughly cover [these](https://github.com/search?q=repo%3Aprotocolbuffers%2Fprotobuf%20path%3A%2F.*python.*%5C.h%2F&type=code) files, I think. Some of these are already part of `libprotobuf`, in particular:
```
include/google/protobuf/compiler/python/generator.h
include/google/protobuf/compiler/python/pyi_generator.h
include/google/protobuf/compiler/python/python_generator.h
```

I guess we could let conda deduplicate this if we host-depend on `libprotobuf` for building this.
