### ISSUE TITLE
Windows conda package with static libraries is over 100 megabytes

### ISSUE THREAD

**Issue by wesm** [conda-forge/libprotobuf-feedstock#24]
See https://anaconda.org/conda-forge/libprotobuf/files

Apparently the jump to static libraries caused the tarball size to go from 2.0 MB to 137 MB. Suffice to say this is unacceptable. I'm looking into what's going on...

**Comment by wesm** [comment]
What a mess:

```
λ ls -lh Library\lib\
total 701M
-rw-r--r-- 1 wesmc 197609 3.7M Mar  3 04:30 libprotobuf.lib
-rw-r--r-- 1 wesmc 197609 259M Mar  3 04:45 libprotobuf_static.lib
-rw-r--r-- 1 wesmc 197609 797K Mar  3 04:28 libprotobuf-lite.lib
-rw-r--r-- 1 wesmc 197609  50M Mar  3 04:44 libprotobuf-lite_static.lib
-rw-r--r-- 1 wesmc 197609 365K Mar  3 04:32 libprotoc.lib
-rw-r--r-- 1 wesmc 197609 389M Mar  3 04:47 libprotoc_static.lib
drwxr-xr-x 1 wesmc 197609    0 Mar  8 14:11 pkgconfig/
```

So bottom line we have to turn off the static libs here and deal with it in downstream projects. If someone needs the static libs in a conda package we'll need to create a separate `libprotobuf-static` or something

**Comment by jjhelmus** [comment]
One option would be to use [multiple outputs](https://conda.io/projects/conda-build/en/latest/source/resources/define-metadata.html#outputs-section) to create a `libprotobuf-static` package from within the same recipe.

**Comment by jakirkham** [comment]
Agree with @jjhelmus that having a split package would be a nice solution here.

**Comment by wesm** [comment]
Seems reasonable to me. This is not a necessity for anything I'm doing but I would support someone else doing this work

**Comment by dougalsutherland** [comment]
I'd use a `libprotobuf-static` split-output recipe (in the shogun feedstock), though not high-priority enough that I'm going to make the package right now. :)

**Comment by jschueller** [comment]
seems like static package was removed, this can be closed

**Comment by jakirkham** [comment]
Yep and they were split out with PR ( https://github.com/conda-forge/libprotobuf-feedstock/pull/61 ).
