### ISSUE TITLE
Master failed due to new conda-build version

### ISSUE THREAD

**Issue by xhochy** [conda-forge/libprotobuf-feedstock#35]
With the new `conda-build-3.18.7` we seen to be running again into https://github.com/conda/conda-build/issues/3583, logs: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=49368&view=logs

**Comment by jakirkham** [comment]
Is this still relevant?

**Comment by xhochy** [comment]
Yes, master failed again as we got HTTP 500 errors from anaconda.org, retrigged the CI.

**Comment by jakirkham** [comment]
Though the HTTP 500 errors are something different, no?

**Comment by xhochy** [comment]
Yes, these were different issue but all green now, closing.
