### ISSUE TITLE
Package is missing a lot of header files

### ISSUE THREAD

**Issue by sodre** [conda-forge/libprotobuf-feedstock#50]
The `libprotobuf` package generated with cmake is incomplete. For example it does not include all the header files found on the source distribution.

The [google/protobuf/stubs/stringprintf.h](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/stubs/stringprintf.h) file is an example of a file that is the source distribution, but is not copied into the [conda-package](#dir-content). Here are the 

<a name=dir-content></a>Contents under Conda's <code>include/google/protobuf/stubs</code> directory:
<details>

```
(libprotobuf) [conda@932a6295fbf9 include]$ ls -la $CONDA_PREFIX/include/google/protobuf/stubs/
total 236
drwxrwxr-x 2 conda conda  4096 Apr 14 09:01 .
drwxrwxr-x 6 conda conda  4096 Apr 14 09:01 ..
-rw-rw-r-- 2 conda conda 11758 Feb 16 07:37 bytestream.h
-rw-rw-r-- 2 conda conda 17078 Feb 16 07:37 callback.h
-rw-rw-r-- 2 conda conda  5688 Feb 16 07:37 casts.h
-rw-rw-r-- 2 conda conda  7308 Feb 16 07:37 common.h
-rw-rw-r-- 2 conda conda  6016 Feb 16 07:37 fastmem.h
-rw-rw-r-- 2 conda conda  4122 Feb 16 07:37 hash.h
-rw-rw-r-- 2 conda conda  8915 Feb 16 07:37 logging.h
-rw-rw-r-- 2 conda conda  4903 Feb 16 07:37 macros.h
-rw-rw-r-- 2 conda conda 31213 Feb 16 07:37 map_util.h
-rw-rw-r-- 2 conda conda  6157 Feb 16 07:37 mutex.h
-rw-rw-r-- 2 conda conda  2184 Feb 16 07:37 once.h
-rw-rw-r-- 2 conda conda  5108 Feb 16 07:37 platform_macros.h
-rw-rw-r-- 2 conda conda 12817 Feb 16 07:37 port.h
-rw-rw-r-- 2 conda conda  3939 Feb 16 07:37 status.h
-rw-rw-r-- 2 conda conda  3283 Feb 16 07:37 stl_util.h
-rw-rw-r-- 2 conda conda 17863 Feb 16 07:37 stringpiece.h
-rw-rw-r-- 2 conda conda 38749 Feb 16 07:37 strutil.h
-rw-rw-r-- 2 conda conda  4834 Feb 16 07:37 template_util.h
(libprotobuf) [conda@932a6295fbf9 include]$ 
```
</details>

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /opt/conda/envs/libprotobuf:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libprotobuf               3.11.4               h8b12597_0    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : libprotobuf
    active env location : /opt/conda/envs/libprotobuf
            shell level : 4
       user config file : /home/conda/.condarc
 populated config files : /opt/conda/.condarc
                          /home/conda/.condarc
          conda version : 4.8.3
    conda-build version : 3.19.2
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.12
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/conda/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/conda/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Linux/4.19.76-linuxkit centos/6.10 glibc/2.12
                UID:GID : 9001:9001
             netrc file : None
           offline mode : False

```
</details>

**Comment by jakirkham** [comment]
AFAICT we are [just calling `make install`]( https://github.com/conda-forge/libprotobuf-feedstock/blob/339eb5b9a3014806e91831ca939bef56ee53ae13/recipe/build.sh#L41 ) and not doing anything custom. Given this, should this issue be raised [upstream]( https://github.com/protocolbuffers/protobuf )?

**Comment by sodre** [comment]
> AFAICT we are [just calling `make install`](https://github.com/conda-forge/libprotobuf-feedstock/blob/339eb5b9a3014806e91831ca939bef56ee53ae13/recipe/build.sh#L41) and not doing anything custom. Given this, should this issue be raised [upstream](https://github.com/protocolbuffers/protobuf)?

Possibly, but the same issue does not show up if one is using the [brew recipe](https://github.com/Homebrew/homebrew-core/blob/master/Formula/protobuf.rb).

I'll try switching away from cmake into plain auto tools for osx and linux to see if it works.

**Comment by sodre** [comment]
> > AFAICT we are [just calling `make install`](https://github.com/conda-forge/libprotobuf-feedstock/blob/339eb5b9a3014806e91831ca939bef56ee53ae13/recipe/build.sh#L41) and not doing anything custom. Given this, should this issue be raised [upstream](https://github.com/protocolbuffers/protobuf)?
> 
> Possibly, but the same issue does not show up if one is using the [brew recipe](https://github.com/Homebrew/homebrew-core/blob/master/Formula/protobuf.rb).
> 
> I'll try switching away from cmake into plain auto tools for osx and linux to see if it works.

I meant to check with brew before posting... they also don't include that file.

@jakirkham, this is looking like an upstream problem. I will look for another distro of libprotobuf and see if it looks the same.

**Comment by isuruf** [comment]
CMake builds were mark broken. So you are using the an autotools build.

**Comment by jakirkham** [comment]
> @jakirkham, this is looking like an upstream problem. I will look for another distro of libprotobuf and see if it looks the same.

Did you come to any conclusion here, @sodre?

**Comment by sodre** [comment]
@jakirkham, I looked at libprotobuf on ubuntu as well. We are all doing the same thing. 

I am going to close the issue here and use the work-a-round in cockroachdb.

**Comment by jakirkham** [comment]
Good to know. Thanks for checking. 🙂

Would it make sense to raise an issue upstream?
