### ISSUE TITLE
Missing static libraries in the last build

### ISSUE THREAD

**Issue by JanuszL** [conda-forge/libprotobuf-feedstock#60]
Issue:
The latest release, like https://anaconda.org/conda-forge/libprotobuf/3.12.3/download/linux-64/libprotobuf-3.12.3-h8b12597_1.tar.bz2 misses static libraries *.a. Only dynamic .so are available. While https://anaconda.org/conda-forge/libprotobuf/3.12.3/download/linux-64/libprotobuf-3.12.3-h8b12597_0.tar.bz2 is good

**Comment by xhochy** [comment]
@JanuszL Please include `libprotobuf-static` in your build (should be available 1h from now).

**Comment by JanuszL** [comment]
It fixes the problem. Thanks!
